<?php

namespace PancakeBundle\Repository;

/**
 * PancakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PancakeRepository extends \Doctrine\ORM\EntityRepository
{
}
